# Generated by Django 5.0.6 on 2026-07-19 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network_report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reflection_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reflection_prompt',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reflection_red_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reflection_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_tier',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20),
        ),
        migrations.CreateModel(
            name='RecipientReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_account_id', models.CharField(db_index=True, max_length=30)),
                ('recipient_bank', models.CharField(blank=True, max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('reported_by_user_id', models.CharField(db_index=True, max_length=100)),
                ('reason', models.CharField(choices=[('impersonation', 'Impersonation'), ('investment', 'Investment scam'), ('romance', 'Romance scam'), ('purchase', 'Goods or services scam'), ('coercion', 'Pressure or coercion'), ('other', 'Other suspicious activity')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_reports', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipientreport',
            constraint=models.UniqueConstraint(fields=('recipient_account_id', 'reported_by_user_id'), name='one_recipient_report_per_user'),
        ),
    ]
