# Generated by Django 5.0.6 on 2026-07-19 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_seed_shared_recipient_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('awaiting_review', 'Awaiting security review'), ('review_approved', 'Approved by security review'), ('blocked', 'Blocked by security review'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed after flag')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SecurityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by_user_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled by sender')], default='pending', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('reviewed_by_user_id', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_review', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
